# Generated by Django 4.2.1 on 2023-05-23 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantly_app', '0002_member_alter_membre_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Membre',
        ),
    ]
